name 'cb_dvo_osUpdate'
maintainer 'Ray Crawford'
maintainer_email 'ray_crawford@trekbikes.com'
license 'all_rights'
description 'Installs/Configures cb_dvo_osUpdate'
long_description 'Installs/Configures cb_dvo_osUpdate'
issues_url 'https://bitbucket.org/trekbikes/cb_dvo_adJoin/issues'
source_url 'https://bitbucket.org/trekbikes/cb_dvo_adJoin/src'
version '0.1.1'

chef_version '~> 12'
supports 'centos'
